[package]
name = "botframework"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "botframework"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0"
pyo3 = { version = "0.16.3", features = ["extension-module"] }
reqwest = { version = "0.11", features = ["json", "blocking"] }
tokio = { version = "1", features = ["full"] }
tungstenite = "0.17.0"
tokio-tungstenite = { version = "0.17.1", features = ["native-tls", "stream"] }
serde_json = "1.0.78"
url = "2.2.2"

futures-util = "*"


