name: Linux build package

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: debug
      run: |
        echo '::echo::on'
        pwd
        cd rust/botframework
        pwd
        ls
    - name: Build
      run: cd rust/botframework; cargo build --verbose
    - name: Build Package
      run: |
        cd rust/botframework; 
        python -m pip install build
        python -m build .
    - name: linux-wheels
      uses: actions/upload-artifact@v3
      with:
        name: linux-wheel
        path: rust/botframework/dist/*

