name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Wheel
      run: cd rust/botframework; cargo build --verbose
    - name: Build Package
      run: |
        cd rust/botframework; 
        python -m pip install build
        python -m build .
    - name: upload windows-wheels
      uses: actions/upload-artifact@v3
      with:
        name: linux-wheel
        path: rust/botframework/dist/*.whl
  

